services:
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: "propedia"
            MYSQL_DATABASE: "laravel"
        ports:
            - "3306:3306"
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
